-- =======================================================
-- Service VIP Sheet - Full Supabase Database Schema
-- Run this script in the Supabase SQL Editor
-- =======================================================

-- 1. USERS
CREATE TABLE IF NOT EXISTS users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    username TEXT UNIQUE NOT NULL,
    email TEXT,
    password TEXT NOT NULL,
    role TEXT DEFAULT 'moderator',
    permissions JSONB DEFAULT '[]'::jsonb,
    base_salary NUMERIC DEFAULT 0,
    vodafone_cash TEXT DEFAULT '',
    token TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. PRODUCTS
CREATE TABLE IF NOT EXISTS products (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    price NUMERIC DEFAULT 0,
    duration INTEGER DEFAULT 30,
    description TEXT DEFAULT '',
    category TEXT DEFAULT '',
    inventory_product TEXT DEFAULT '',
    fulfillment_type TEXT DEFAULT 'client_account',
    sort_order INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. INVENTORY SECTIONS
CREATE TABLE IF NOT EXISTS inventory_sections (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. ACCOUNTS (Inventory)
CREATE TABLE IF NOT EXISTS accounts (
    id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
    product_name TEXT,
    email TEXT,
    password TEXT,
    two_fa TEXT DEFAULT '',
    status TEXT DEFAULT 'available',
    allowed_uses INTEGER DEFAULT 1,
    current_uses INTEGER DEFAULT 0,
    created_by TEXT DEFAULT 'Admin',
    is_workspace BOOLEAN DEFAULT false,
    workspace_members INTEGER DEFAULT 0,
    workspace_cost NUMERIC DEFAULT 0,
    notes TEXT DEFAULT '',
    buyer_name TEXT DEFAULT '',
    buyer_phone TEXT DEFAULT '',
    buyer_profile_link TEXT DEFAULT '',
    buyer_device TEXT DEFAULT '',
    assigned_at TIMESTAMPTZ,
    expires_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. CUSTOMERS
CREATE TABLE IF NOT EXISTS customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    phone TEXT DEFAULT '',
    email TEXT DEFAULT '',
    contact_channel TEXT DEFAULT 'واتساب',
    last_order_date TIMESTAMPTZ DEFAULT NOW(),
    notes TEXT DEFAULT '',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. SALES
CREATE TABLE IF NOT EXISTS sales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE DEFAULT CURRENT_DATE,
    product_name TEXT,
    original_price NUMERIC DEFAULT 0,
    discount NUMERIC DEFAULT 0,
    final_price NUMERIC DEFAULT 0,
    duration INTEGER DEFAULT 30,
    expiry_date DATE,
    customer_id BIGINT,
    customer_name TEXT DEFAULT '',
    customer_phone TEXT DEFAULT '',
    customer_email TEXT DEFAULT '',
    contact_channel TEXT DEFAULT 'واتساب',
    is_paid BOOLEAN DEFAULT false,
    remaining_amount NUMERIC DEFAULT 0,
    payment_method TEXT DEFAULT '',
    wallet_id BIGINT,
    wallet_name TEXT DEFAULT '',
    notes TEXT DEFAULT '',
    moderator TEXT DEFAULT 'Admin',
    assigned_account_email TEXT DEFAULT '',
    assigned_account_id TEXT,
    from_inventory BOOLEAN DEFAULT false,
    sale_type TEXT DEFAULT 'personal',
    workspace_email TEXT DEFAULT '',
    is_activated BOOLEAN DEFAULT false,
    customer_password TEXT DEFAULT '',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. EXPENSES
CREATE TABLE IF NOT EXISTS expenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount NUMERIC DEFAULT 0,
    category TEXT DEFAULT '',
    description TEXT DEFAULT '',
    wallet_id BIGINT,
    wallet_name TEXT DEFAULT '',
    date DATE DEFAULT CURRENT_DATE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. WALLETS
CREATE TABLE IF NOT EXISTS wallets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    balance NUMERIC DEFAULT 0,
    type TEXT DEFAULT 'cash',
    account_number TEXT DEFAULT '',
    notes TEXT DEFAULT '',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 9. WALLET TRANSACTIONS
CREATE TABLE IF NOT EXISTS wallet_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wallet_id BIGINT,
    type TEXT NOT NULL,
    amount NUMERIC DEFAULT 0,
    balance_after NUMERIC DEFAULT 0,
    description TEXT DEFAULT '',
    reference_type TEXT DEFAULT 'manual',
    created_by TEXT DEFAULT 'Admin',
    date TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 10. ATTENDANCE
CREATE TABLE IF NOT EXISTS attendance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT,
    date TEXT NOT NULL,
    check_in TEXT,
    bonus NUMERIC DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 11. PROBLEMS
CREATE TABLE IF NOT EXISTS problems (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id BIGINT,
    customer_name TEXT DEFAULT '',
    phone_number TEXT DEFAULT '',
    product_name TEXT DEFAULT '',
    description TEXT,
    replacement_account_id TEXT,
    is_resolved BOOLEAN DEFAULT false,
    resolved_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 12. QUICK LINKS
CREATE TABLE IF NOT EXISTS quick_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label TEXT NOT NULL,
    url TEXT NOT NULL,
    created_by TEXT DEFAULT 'Admin',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 13. EMPLOYEES
CREATE TABLE IF NOT EXISTS employees (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    phone TEXT DEFAULT '',
    role TEXT DEFAULT '',
    base_salary NUMERIC DEFAULT 0,
    bonus NUMERIC DEFAULT 0,
    deductions NUMERIC DEFAULT 0,
    absence_days INTEGER DEFAULT 0,
    absence_deduction_per_day NUMERIC DEFAULT 0,
    notes TEXT DEFAULT '',
    is_active BOOLEAN DEFAULT true,
    join_date DATE DEFAULT CURRENT_DATE,
    pay_day TEXT DEFAULT 'thursday',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 14. SALARY PAYMENTS
CREATE TABLE IF NOT EXISTS salary_payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT,
    amount NUMERIC DEFAULT 0,
    payment_date DATE DEFAULT CURRENT_DATE,
    notes TEXT DEFAULT '',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 15. EMPLOYEE ACTIONS
CREATE TABLE IF NOT EXISTS employee_actions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT,
    action_type TEXT NOT NULL,
    amount NUMERIC DEFAULT 0,
    description TEXT DEFAULT '',
    action_date DATE DEFAULT CURRENT_DATE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 16. CUSTOM SHEETS DATA (Syncing all sheet records across devices)
CREATE TABLE IF NOT EXISTS custom_sheets_data (
    sheet_id TEXT PRIMARY KEY,
    records JSONB NOT NULL DEFAULT '[]'::jsonb,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 17. CUSTOM SHEETS CONFIG
CREATE TABLE IF NOT EXISTS custom_sheets_config (
    id TEXT PRIMARY KEY DEFAULT 'main_config',
    config JSONB NOT NULL DEFAULT '[]'::jsonb,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- =======================================================
-- DISABLE ROW LEVEL SECURITY (RLS) & ALLOW PUBLIC ACCESS
-- =======================================================
DO $$
DECLARE
    tbl text;
    tables text[] := ARRAY[
        'users', 'products', 'inventory_sections', 'accounts', 'customers',
        'sales', 'expenses', 'wallets', 'wallet_transactions', 'attendance',
        'problems', 'quick_links', 'employees', 'salary_payments', 'employee_actions',
        'custom_sheets_data', 'custom_sheets_config'
    ];
BEGIN
    FOREACH tbl IN ARRAY tables LOOP
        -- تعطيل RLS
        EXECUTE format('ALTER TABLE IF EXISTS public.%I DISABLE ROW LEVEL SECURITY;', tbl);
        
        -- حذف السياسات القديمة إن وجدت
        EXECUTE format('DROP POLICY IF EXISTS "Allow all for public" ON public.%I;', tbl);
        
        -- إنشاء سياسة وصول شاملة حتى لو تم تفعيل RLS مستقبلاً
        EXECUTE format('CREATE POLICY "Allow all for public" ON public.%I FOR ALL TO public USING (true) WITH CHECK (true);', tbl);
    END LOOP;
END $$;

-- منح كامل الصلاحيات لجميع الأدوار
GRANT USAGE ON SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON ALL TABLES IN SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON ALL ROUTINES IN SCHEMA public TO anon, authenticated, service_role;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON ROUTINES TO anon, authenticated, service_role;

-- =======================================================
-- SEED & UPDATE DEFAULT ADMIN USER
-- =======================================================
-- 1. تحديث أي حساب أدمن سابق للبيانات الجديدة
UPDATE users 
SET username = 'Admin@servicevip.com',
    email = 'Admin@servicevip.com',
    password = 'Service2030@',
    role = 'admin',
    permissions = '["all"]'::jsonb
WHERE username ILIKE 'support@servicevip.com' 
   OR email ILIKE 'support@servicevip.com'
   OR (role = 'admin' AND (username ILIKE 'admin' OR email ILIKE 'admin%'));

-- 2. حذف وإلغاء أي حساب قديم متبقٍ باسم support@servicevip.com
DELETE FROM users 
WHERE (username ILIKE 'support@servicevip.com' OR email ILIKE 'support@servicevip.com')
  AND username NOT ILIKE 'Admin@servicevip.com';

-- 3. إضافة أو تثبيت الأدمن الجديد بالبيانات الصحيحة
INSERT INTO users (username, email, password, role, permissions)
VALUES (
    'Admin@servicevip.com',
    'Admin@servicevip.com',
    'Service2030@',
    'admin',
    '["all"]'::jsonb
)
ON CONFLICT (username) DO UPDATE 
SET password = EXCLUDED.password,
    email = EXCLUDED.email,
    role = EXCLUDED.role,
    permissions = EXCLUDED.permissions;


